select PAYMENT.id, type_id, amount, payment_date, student_id from PAYMENT join PAYMENTTYPE P2 on P2.ID = PAYMENT.TYPE_ID where NAME = 'MONTHLY';
select MARK.ID, STUDENT_ID, SUBJECT_ID, MARK from MARK join SUBJECT S on S.ID = MARK.SUBJECT_ID where S.NAME = 'Art';
select * from STUDENT join PAYMENT P2 on STUDENT.ID = P2.STUDENT_ID join PAYMENTTYPE P3 on P3.ID = P2.TYPE_ID where p3.NAME = 'WEEKLY';
select STUDENT.ID, STUDENT.NAME, STUDENT.BIRTHDAY, STUDENT.GROUPNUMBER from STUDENT join MARK M on STUDENT.ID = M.STUDENT_ID join SUBJECT S on M.SUBJECT_ID = S.ID where S.NAME = 'Math';